package ru.avdeev.chat.commons;

public enum MessageType {
    REQUEST_AUTH ("/REQUEST_AUTH"),
    RESPONSE_AUTH_OK ("/RESPONSE_AUTH_OK"),
    RESPONSE_AUTH_ERROR ("/RESPONSE_AUTH_ERROR"),

    REQUEST_USER_NAME_CHANGE("/REQUEST_USER_NAME_CHANGE"),
    RESPONSE_USER_NAME_CHANGE_OK("/RESPONSE_USER_NAME_CHANGE_OK"),
    RESPONSE_USER_NAME_CHANGE_ERROR("/RESPONSE_USER_NAME_CHANGE_ERROR"),

    REQUEST_USER_PASSWORD_CHANGE("/REQUEST_USER_PASSWORD_CHANGE"),
    RESPONSE_USER_PASSWORD_CHANGE_OK("/RESPONSE_USER_PASSWORD_CHANGE_OK"),
    RESPONSE_USER_PASSWORD_CHANGE_ERROR("RESPONSE_USER_PASSWORD_CHANGE_ERROR"),

    SEND_ALL ("/SEND_ALL"),
    SEND_PRIVATE ("/SEND_PRIVATE"),

    USER_ONLINE ("/USER_ONLINE"),
    USER_OFFLINE ("/USER_OFFLINE"),

    UNDEFINED ("/UNDEFINED");


    private final String value;

    MessageType(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value;
    }
}
